function my_project_controller(varargin)
close all; clc;

runtime_options = parse_runtime_options(varargin{:});
project_directory = fileparts(fileparts(fileparts(mfilename('fullpath'))));
simulator_root = fullfile(project_directory, 'external', 'mujoco_wheeled_uav_simulator');
params_path = resolve_params_path(project_directory, runtime_options.params_path);
generated_xml_directory = fullfile(project_directory, 'build', 'generated_xml');

controller_session = controller_shared.initialize_controller_session( ...
    project_directory, ...
    runtime_options, ...
    'target_ip', '127.0.0.1', ...
    'simulator_root', simulator_root, ...
    'params_path', params_path, ...
    'generated_xml_directory', generated_xml_directory ...
);
vehicle_params = controller_session.vehicle_params;
instance_options = controller_session.instance_options;
controller_socket = controller_session.controller_socket;
socket_cleanup_handler = onCleanup(@() controller_shared.cleanup_controller_socket(controller_socket)); %#ok<NASGU>
simulator_cleanup_handler = onCleanup(@() controller_shared.cleanup_simulator_process(controller_session.simulator_process_id, controller_session.simulator_options)); %#ok<NASGU>

controller_config = controller_shared.build_controller_config(vehicle_params, 'target_position', [0.0; 0.0; 1.5]);
[allocation_matrix, mixer] = controller_shared.build_allocation_and_mixer(vehicle_params);
command_options = controller_shared.build_command_options(vehicle_params.command_mode, vehicle_params.thrust_coefficient);

logging_options = struct( ...
    'save_mode', 'finalize', ...
    'periodic_interval_seconds', 30.0, ...
    'print_save_events', true, ...
    'directory_name', 'logs', ...
    'file_prefix', ['project_hover' instance_options.file_suffix] ...
);

logger = simulation_logger(project_directory, struct( ...
    'controller', 'my_project_controller', ...
    'command_mode', command_options.input_mode, ...
    'instance_id', instance_options.instance_id, ...
    'instance_label', instance_options.label, ...
    'params_path', params_path, ...
    'simulator_root', simulator_root, ...
    'generated_xml_directory', generated_xml_directory, ...
    'target_position', controller_config.target_position, ...
    'position_gain', controller_config.position_gain, ...
    'velocity_gain', controller_config.velocity_gain, ...
    'attitude_gain', controller_config.attitude_gain, ...
    'angular_velocity_gain', controller_config.angular_velocity_gain, ...
    'desired_heading', controller_config.desired_heading, ...
    'allocation_matrix', allocation_matrix, ...
    'mixer', mixer ...
), logging_options);
cleanup_handler = onCleanup(@() controller_shared.finalize_controller_run(logger)); %#ok<NASGU>

fprintf('Project controller started (%s). Ctrl+C to stop.\n', instance_options.label);

while true
    state = controller_shared.read_latest_state(controller_socket);
    if isempty(state)
        continue;
    end

    rotor_thrusts = controller_shared.compute_hover_control( ...
        state, ...
        controller_config.target_position, ...
        controller_config.desired_heading, ...
        vehicle_params.mass, ...
        vehicle_params.gravity, ...
        controller_config.position_gain, ...
        controller_config.velocity_gain, ...
        controller_config.attitude_gain, ...
        controller_config.angular_velocity_gain, ...
        mixer, ...
        vehicle_params.max_rotor_thrust ...
    );

    control_command = controller_shared.build_control_command(rotor_thrusts, command_options);
    controller_shared.send_control_command(controller_socket, control_command, controller_session.target_ip, controller_session.target_port);
    logger.append(state, control_command, controller_config.target_position);
end
end


function params_path = resolve_params_path(project_directory, override_path)
if ~isempty(override_path)
    params_path = override_path;
    return;
end

candidate = fullfile(project_directory, 'configs', 'vehicle', 'vehicle_params.project.json');
if isfile(candidate)
    params_path = candidate;
    return;
end

params_path = fullfile(project_directory, 'external', 'mujoco_wheeled_uav_simulator', 'vehicle_params.json');
end


function runtime_options = parse_runtime_options(varargin)
parser = inputParser;
addParameter(parser, 'instance_id', 0, @(value) validateattributes(value, {'numeric'}, {'scalar', 'integer', 'nonnegative'}));
addParameter(parser, 'auto_launch', false, @(value) islogical(value) || (isnumeric(value) && isscalar(value)));
addParameter(parser, 'shutdown_on_exit', false, @(value) islogical(value) || (isnumeric(value) && isscalar(value)));
addParameter(parser, 'params_path', '', @(value) ischar(value) || (isstring(value) && isscalar(value)));
parse(parser, varargin{:});

runtime_options = parser.Results;
runtime_options.instance_id = double(runtime_options.instance_id);
runtime_options.auto_launch = logical(runtime_options.auto_launch);
runtime_options.shutdown_on_exit = logical(runtime_options.shutdown_on_exit);
runtime_options.params_path = char(runtime_options.params_path);
end